### ISSUE TITLE
Submit report

### ISSUE THREAD

**Issue by elliotblackburn** [BlueHatbRit/scaffold#67]
The following all need completing in the specified order to submit the project for grading.

## Todo

- [x] Purchase 3 sets of binding materials from the SU and a CD.
- [x] Burn all project files onto the CD.
- [x] Print 3 copies **without appendices** with colour (as required), 3 copies allows for a screw up.
- [x] Ask someone at the library to demo how to bind them.
- [x] Bind all three copies.
- [x] Attach the CD to one of the copies.
- [x] Submit the report with CD + one of the other reports into the Smeaton faculty office.
- [x] Submit final PDF (including appendices) to SPMS.

Once all of these are done, the project will be completely submitted!
